### ISSUE TITLE
the json from config from visual code seems invalid json

### ISSUE THREAD

**Issue by silviuchiric** [stuartmccoll/hugo-theme-refresh#18]
Hi

while validating the json in VC with Pretty Json or online with https://jsonlint.com/ returns:

Error: Parse error on line 1:
...aultProfile.windows": "WSL","terminal.i
-----------------------^
Expecting 'EOF', '}', ',', ']', got ':'

**Comment by stuartmccoll** [comment]
Hi,

Thanks for raising this.

The key/value pairs within the JSON you mentioned expect to be inside an enclosing set of curly braces within the `settings.json` file. This wasn't obvious from the blog post you mentioned, so I've updated it accordingly.

Thanks,
Stu
